### ISSUE TITLE
need to disconnect and reconnect before each print start

### ISSUE THREAD

**Issue by hashoom8** [jneilliii/OctoPrint-BambuPrinter#9]
I'm printing through bambu studio 

but I need to disconnect and reconnect before each print start because octoprint did not detect the print started

**Comment by jneilliii** [comment]
on the terminal tab do you see lines like `{filename} open failed` repeating?

**Comment by hashoom8** [comment]
> on the terminal tab do you see lines like `{filename} open failed` repeating?

yes 
![Screenshot 2024-03-02 203428](https://github.com/jneilliii/OctoPrint-BambuPrinter/assets/46507374/06b4fbb4-56db-4be4-9259-0198b63f565c)

**Comment by jneilliii** [comment]
I think I've fixed that in the last release. it should reload the filelist if the file isn't found in the file list. give version 0.0.16 a try and let me know.

**Comment by hashoom8** [comment]
> I think I've fixed that in the last release. it should reload the filelist if the file isn't found in the file list. give version 0.0.16 a try and let me know.

will i did the update turned on the Printer and start the connection , start a print through bambu studio , and its not showing that I'm printing , i had to disconnect and reconnect 

![Screenshot 2024-03-03 192132](https://github.com/jneilliii/OctoPrint-BambuPrinter/assets/46507374/5ebc64a2-2eee-441b-88cf-e063b454b023)

**Comment by jneilliii** [comment]
please enable debug logging for the bambu related entries in OctoPrint's logging section. and try the process again and then share your octoprint.log.

**Comment by hashoom8** [comment]
> please enable debug logging for the bambu related entries in OctoPrint's logging section. and try the process again and then share your octoprint.log.

i found out what happening 

when i start a print from the slicer , octoprint can't find the file in the sd card , so when i do reconnect or refresh sd card files octoprint  detect it and showing print started

**Comment by jneilliii** [comment]
Thanks for the additional information. That is something that I've been trying to fix for some time. It mostly works for me and my X1 but I suspect the lower powered A1/P1 devices are still struggling with the solution.

**Comment by JanUmbach** [comment]
I'm having the same problem with my P1S.

I would love to see a fix for that :) and btw nice plugin you've written so far! :D

**Comment by jneilliii** [comment]
I need more details as to why this is happening. When you send a file to print from slicer OctoPrint should start to pick up that a print was started remotely, it then checks to see if the filename reported as printing from the printer is in OctoPrint's cached file list or not from initial connection. If it's not, it then requests an updated file list from the printer. When this happens for you guys are you seeing any messages in the terminal tab about printing <file name>? Enabling logging for the bambu items in OctoPrint's logging section and reproduce the issue and then share the octoprint.log and any other bambu logs generated.

**Comment by JanUmbach** [comment]
When I start a print from slicer, octoprint will refresh the file list, but there is one problem. The file has 0 bytes, the console spams:

```
Send: N912 M105*45
Recv: T:209.00/ 170.00 B:64.00/ 65.00 @:64
Recv: ok
Send: N913 M27*29
Recv: Not SD printing
Recv: ok
Send: N914 M27*26
Recv: Not SD printing
Recv: ok
Recv: File opened: testttt.3mf  Size: 0
Recv: File selected
Recv: Done printing file
Send: N924 M105*40
Recv: T:200.00/ 170.00 B:64.00/ 65.00 @:64
Recv: ok
Send: N925 M27*24
Recv: Not SD printing
Recv: ok
Send: N926 M27*27
Recv: Not SD printing
Recv: ok
Recv: File opened: testttt.3mf  Size: 0
Recv: File selected
Recv: Done printing file
Send: N927 M105*43
Recv: T:197.00/ 170.00 B:64.00/ 65.00 @:64
Recv: ok
Send: N928 M27*21
Recv: Not SD printing
Recv: ok
Send: N929 M27*20
Recv: Not SD printing
Recv: ok
Recv: File opened: testttt.3mf  Size: 0
Recv: File selected
Recv: Done printing file
Send: N930 M20 L T*3
Recv: Begin file list
Recv: test.3mf 17848767 0x58a8b5ce "test.3mf"
Recv: testt.3mf 5588609 0x58aaa3b6 "testt.3mf"
Recv: testttt.3mf 5588609 0x58aaa419 "testttt.3mf"
Recv: End file list
Recv: ok
Send: N931 M105*44
Recv: T:196.00/ 170.00 B:64.00/ 65.00 @:64
Recv: ok
Send: N932 M27*30
Recv: Not SD printing
Recv: ok
Recv: File opened: testttt.3mf  Size: 5588609
Recv: File selected
Recv: SD printing byte 0/5588609
Send: N933 M27*31
Recv: SD printing byte 55886/5588609
Changing monitoring state from "Operational" to "Starting print from SD"
Recv: ok
Changing monitoring state from "Starting print from SD" to "Printing from SD"
Send: N934 M105*41
Recv: T:193.00/ 170.00 B:64.00/ 65.00 @:64
Recv: ok
Send: N935 M27*25
Recv: SD printing byte 55886/5588609
Recv: ok
Send: N936 M27*26
Recv: SD printing byte 55886/5588609
Recv: ok
Recv: SD printing byte 55886/5588609
Send: N937 M27*27
Recv: SD printing byte 55886/5588609
Recv: ok
Send: N938 M27*20
Recv: SD printing byte 55886/5588609
Recv: ok
Send: N939 M27*21
Recv: SD printing byte 55886/5588609
Recv: ok
Recv: SD printing byte 55886/5588609
Send: N940 M105*42
Recv: T:186.00/ 170.00 B:63.00/ 65.00 @:64
Recv: ok
Send: N941 M27*26
Recv: SD printing byte 55886/5588609
Recv: ok
```


after i pressed manually "update file list" in octoprint (Recv: Begin file list) it recognizes, that i have started a print.
Also when i have started the same filename from slicer, doesn't reload i think

octoprint.log
```
2024-05-10 13:15:02,626 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:03,627 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:04,627 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:05,563 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:05,627 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:06,628 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:07,628 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:08,629 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:09,629 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:10,564 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:10,629 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:11,631 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:12,631 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:13,631 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:14,631 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:15,564 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:15,631 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:16,632 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:17,633 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:18,632 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:19,634 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:20,564 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:20,633 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:21,634 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:22,635 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:23,634 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:24,635 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:25,565 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:25,635 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:26,636 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:27,637 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:28,637 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:28,909 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3, check_already_open=False
2024-05-10 13:15:28,909 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3
2024-05-10 13:15:29,638 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:30,565 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:30,638 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:31,640 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:32,234 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFiles return: {'testttt.3mf': {'dosname': 'testttt.3mf', 'name': 'testttt.3mf', 'path': 'cache/testttt.3mf', 'size': 5588609, 'timestamp': '0x58aaa419'}, 'testttt3.3mf': {'dosname': 'testttt3.3mf', 'name': 'testttt3.3mf', 'path': 'cache/testttt3.3mf', 'size': 0, 'timestamp': '0x58aaa9ed'}}
2024-05-10 13:15:32,234 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3
2024-05-10 13:15:32,234 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:15:32,238 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt.3mf
2024-05-10 13:15:32,239 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:15:32,640 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:32,946 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:15:32,946 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:15:32,946 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:15:32,947 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:15:32,948 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:15:32,960 - octoprint.plugins.obico - ERROR - 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 136, in get_file_metadata
    return plugin._file_manager._storage_managers.get(origin).get_metadata(path) or {}
AttributeError: 'NoneType' object has no attribute 'get_metadata'
2024-05-10 13:15:33,641 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:34,643 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:34,961 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:15:34,961 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:15:34,961 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:15:34,962 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:15:34,962 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:15:34,964 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:15:35,565 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:15:35,643 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:36,646 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:15:36,987 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:15:36,987 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:15:36,987 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:15:36,988 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:15:36,988 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:15:36,990 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed

.. I've cut this

2024-05-10 13:23:43,688 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:43,858 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:44,256 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:23:44,256 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:23:44,256 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:23:44,256 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:23:44,259 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:44,858 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:45,695 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:45,862 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:46,298 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:23:46,298 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:23:46,298 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:23:46,299 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:23:46,300 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:23:46,300 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:46,860 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:47,688 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:47,860 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:48,325 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:23:48,325 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:23:48,325 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:23:48,326 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:48,326 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:23:48,327 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:23:48,860 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:49,689 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:49,861 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:50,862 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:51,690 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:51,862 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:52,374 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:23:52,374 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:23:52,374 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:23:52,375 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:52,376 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - SD File Print: cache/testttt3.3mf
2024-05-10 13:23:52,376 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:23:52,862 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:53,487 - octoprint.plugins.obico - ERROR - 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 136, in get_file_metadata
    return plugin._file_manager._storage_managers.get(origin).get_metadata(path) or {}
AttributeError: 'NoneType' object has no attribute 'get_metadata'

# here i have reloaded the files manually and it now works

2024-05-10 13:23:56,163 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFiles return: {'testttt.3mf': {'dosname': 'testttt.3mf', 'name': 'testttt.3mf', 'path': 'cache/testttt.3mf', 'size': 5588609, 'timestamp': '0x58aaa419'}, 'testttt3.3mf': {'dosname': 'testttt3.3mf', 'name': 'testttt3.3mf', 'path': 'cache/testttt3.3mf', 'size': 5576501, 'timestamp': '0x58aaaa05'}}
2024-05-10 13:23:56,163 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M20 L T
2024-05-10 13:23:56,173 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:56,179 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:56,864 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:57,691 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:57,864 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:58,073 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _selectSdFile: testttt3.3mf, check_already_open=False
2024-05-10 13:23:58,073 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _getSdFileData: testttt3.3mf
2024-05-10 13:23:58,073 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - _startSdPrint: from_printer=True
2024-05-10 13:23:58,074 - octoprint.printer.standard.job - INFO - Print job selected - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:58,075 - octoprint.plugins.bambu_printer.BambuPrinter - INFO - print resumed
2024-05-10 13:23:58,865 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:23:58,866 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Starting print from SD"
2024-05-10 13:23:58,868 - octoprint.printer.standard.job - INFO - Print job started - origin: sdcard, path: testttt3.3mf, owner: None, user: None
2024-05-10 13:23:58,873 - octoprint.util.comm - INFO - Changing monitoring state from "Starting print from SD" to "Printing from SD"
2024-05-10 13:23:58,875 - octoprint.plugins.obico - ERROR - 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 136, in get_file_metadata
    return plugin._file_manager._storage_managers.get(origin).get_metadata(path) or {}
AttributeError: 'NoneType' object has no attribute 'get_metadata'
2024-05-10 13:23:58,896 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2024-05-10 13:23:58,897 - octoprint.plugins.obico - ERROR - Exception
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/utils.py", line 355, in get_file_metadata
    return file_manager.get_metadata(path=target_path, destination=location) # Compatibility with OctoPrint 1.9.x and earlier.
TypeError: FileManager.get_metadata() got an unexpected keyword argument 'destination'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/__init__.py", line 185, in on_event
    event_payload = _print_job_tracker.on_event(self, event, payload)
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 47, in on_event
    self.set_obico_g_code_file_id(find_obico_g_code_file_id(payload))
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 27, in find_obico_g_code_file_id
    md5_hash = get_file_metadata(plugin._file_manager, payload['path'], payload['origin']).get('hash')
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/utils.py", line 357, in get_file_metadata
    return file_manager.get_metadata(path=target_path, location=location)
  File "/usr/local/lib/python3.10/site-packages/octoprint/filemanager/__init__.py", line 950, in get_metadata
    return self._storage(location).get_metadata(path)
  File "/usr/local/lib/python3.10/site-packages/octoprint/filemanager/__init__.py", line 1076, in _storage
    raise NoSuchStorage(f"No storage configured for destination {location}")
octoprint.filemanager.NoSuchStorage: No storage configured for destination sdcard
2024-05-10 13:23:59,051 - octoprint.plugins.obico - ERROR - 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 136, in get_file_metadata
    return plugin._file_manager._storage_managers.get(origin).get_metadata(path) or {}
AttributeError: 'NoneType' object has no attribute 'get_metadata'
2024-05-10 13:23:59,349 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2024-05-10 13:23:59,691 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:23:59,865 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:00,866 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:01,866 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:02,867 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:03,867 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:04,692 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:04,867 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:05,867 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:06,869 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:07,868 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:08,869 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:09,502 - octoprint.plugins.obico - ERROR - 'NoneType' object has no attribute 'get_metadata'
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_obico/print_job_tracker.py", line 136, in get_file_metadata
    return plugin._file_manager._storage_managers.get(origin).get_metadata(path) or {}
AttributeError: 'NoneType' object has no attribute 'get_metadata'
2024-05-10 13:24:09,693 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:09,869 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:10,871 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:11,870 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:12,871 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:13,871 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:14,693 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:14,871 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:15,874 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:16,872 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:17,873 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:18,875 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:19,693 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:19,874 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:20,875 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:21,875 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:22,875 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:23,876 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:24,693 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:24,876 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:25,876 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:26,877 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:27,878 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:28,903 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:29,694 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M105
2024-05-10 13:24:29,890 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:30,891 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:31,891 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
2024-05-10 13:24:32,891 - octoprint.plugins.bambu_printer.BambuPrinter - DEBUG - M27
```
Sorry, obico prints currently a lot of error messages

So maybe you're refreshing to early the print file?

Also my resend ratio is going crazy `0 / 5.4K (0%)`. Is it also a bug? I think the count gets faster up over time

Thank you for your time :)

**Comment by jneilliii** [comment]
This is hard to figure out with a printer that works perfectly fine. I've added some additional logging info in a separate branch. Could you please install by copying/pasting the URL below into plugin manager > get more > ,,,from URL and clicking install, restart OctoPrint, reproduce the issue, and share the full log (you can use the paperclip button in comment editor)

```
https://github.com/jneilliii/OctoPrint-BambuPrinter/archive/refs/heads/bugfix/a1.zip
```

**Comment by JanUmbach** [comment]
I have started two prints. `xyzCalibration_cube2` worked for whatever reason. And `xyzCalibration_TEST` is the same issue, so I have manually refreshed the files.

[octoprint.log](https://github.com/jneilliii/OctoPrint-BambuPrinter/files/15285471/octoprint.log)

**Comment by jneilliii** [comment]
Can you share with me how that file that didn't work was created? I've heard of some weirdness with some of the test cubes in orca slicer being created oddly and some internal things within the file cause some naming inconsistencies. Can you upload the 3mf here (rename 3mf to zip before uploading).

**Comment by JanUmbach** [comment]
[xyzCalibration_TEST.zip](https://github.com/jneilliii/OctoPrint-BambuPrinter/files/15286577/xyzCalibration_TEST.zip)

But this is not the original file as my printer is currently printing. But I can share it in a few hours :)

I also discovered a bug when I clicked on "Print Again" on the A1 display. Your plugin then looks for the file called "cached/myFile.3mf", but will never find it, as there are only files like "myFile.3mf". There's a 'cached' folder on the SD card, and that might lead to issues when reprinting. I'll also reproduce the issue and send you the logs in a few hours.

Thank you for your time :)

**Comment by jneilliii** [comment]
OK, doesn't look like what I was thinking it was related to the cube weirdness of OrcaSlicer. What I don't understand is why it would work for the first one and not the second. The logs are basically showing the same process completed for each but on the second file, the file list returns a file size of 0. but then later down when you manually refresh the file list it shows the correct size. I'm actually really stumped here on this one. The only thing I can think of is a potential downloading files from cloud while the plugin is listing the files during the prepare stage of the print process. Since I don't use cloud mode on my X1 that may be what's happening here. I'd be curious if you were to switch to local only mode if the issue would persist or not.

**Comment by JanUmbach** [comment]
Yes, I'm using the Cloud. Bu I can also try to switch to the local only mode. Maybe because the first one had a smaller file size and was faster processed than the second file with a bigger file size?

**Comment by jneilliii** [comment]
One last question, are you using the plugin in local mode and the printer is in cloud mode, or do you have both connected to cloud?

**Comment by JanUmbach** [comment]
The Plugin is connected with local mode, but the slicer and how I upload my prints are with cloud mode

**Comment by jneilliii** [comment]
I think I have an idea to resolve this. I've just pushed an update to the bugfix/a1 branch to remove the "preparing" gcode_state from processing print start, and hopefully that will allow the printer time enough during that state for downloading the file before getting the file data over ftps. If you can try reinstalling with the same URL as before and restart OctoPrint and see if that gives more consistent results.

**Comment by JanUmbach** [comment]
The fix worked just fine! I've tested two print files and every time the plugin started to recognize it with full file size. I will test more and also my P1S and will let you know for more testing.

Should I open a new issue for the "cached/" filename prefix problem or can I give my logs here in this issue?

**Comment by jneilliii** [comment]
Good news then, hopefully that will help others as well, I'll go ahead and finalize a new release version with these changes incorporated. 

> Should I open a new issue for the "cached/" filename prefix problem or can I give my logs here in this issue?

Please open a separate issue for that with the logs of that print again issue. The plugin does see the files in cache folder, that's how it's able to get the file data from cloud uploaded files anyway, it just flattens all the files into a single root folder on SD card when listing them to OctoPrint.
